### ISSUE TITLE
Feature request: THOSE keyword

### ISSUE THREAD

**Issue by Glowing0v3rlord** [PlasmaFlare/plasma-baba-mods#1]
Hi, I thought a nice addition to the THIS mod would be the those keyword, which is like this but it refers to all of THOSE objects, for example if you have "those is keke" where those points to baba then it turns all babas in the level into kekes. I just thought this would be cool.

**Comment by PlasmaFlare** [comment]
I did think of possible additions like THESE/THOSE/THAT etc. But currently I'm not feeling like making variations of existing texts. Maybe sometime in the future when I want to revisit THIS.
