### ISSUE TITLE
Error when using THIS simultaneously as sentence subject and object to assign BLOCK

### ISSUE THREAD

**Issue by LvlUniverse** [PlasmaFlare/plasma-baba-mods#3]
![is those is](https://user-images.githubusercontent.com/73113811/156896643-bfe20031-1c75-44f1-a2c3-f018645099de.gif)

Assigning any selection-affecting property in the format X IS THIS, and then attempting to also use that THIS text as the subject of a sentence, causes a nonfatal error.
Note in the GIF that there are no actual WALL objects in the selection, or even the level, to be affected by the assignment.

Lua error: Data/Worlds/7world/Lua.th_text_this.lua: 1260: attempted to index a nil value (local 'raycast_simulation_data')

**Comment by PlasmaFlare** [comment]
Recently fixed this (it was a pretty simple fix). Will close this issue when I update the modpack.
