### ISSUE TITLE
Backing out of a restart while STABLE is in effect breaks STABLE rules

### ISSUE THREAD

**Issue by LvlUniverse** [PlasmaFlare/plasma-baba-mods#4]
![unstable](https://user-images.githubusercontent.com/73113811/156938070-ea8bb954-fe61-4fae-9a16-257e637a7697.gif)

If, while an object is STABLE, you press the restart key but then back out of actually restarting at the restart prompt, STABLE breaks.
Each time the glitch is activated, all STABLE objects completely forget the rules they were STABLE with. After the first time the glitch is activated, the STABLE indicators go missing permanently. The erroneous state can be fixed by restarting the level properly.

**Comment by PlasmaFlare** [comment]
Welp, I just tested it myself and it seems to be on Hempuli's side. The modhook that triggers on level restart (which the modpack relies on) actually fires the *moment* you hit the restart button, regardless of the prompt. I reported this to Hempuli on his server.

Thanks for reporting!
