### ISSUE TITLE
MIMIC doesn't work with pointer nouns

### ISSUE THREAD

**Issue by LvlUniverse** [PlasmaFlare/plasma-baba-mods#6]
MIMIC does not function at all with a pointer noun as the subject or object. In the subject slot, the MIMIC rule shows up in the rule list, but none of its logical derivatives show up: eg. THIS (ORB) MIMIC BABA exists, but not ORB IS YOU (MIMIC). In the object slot, no rules show up at all, regardless of the selection target.

I'm assuming this is a 'won't fix', but it's good to have that decision documented somewhere public.

**Comment by LvlUniverse** [comment]
Looking more carefully, this is actually among the list of bugs that you mentioned "revolve around the same janky way that code() handles subrules". My apologies; I'll avoid reporting any more of those.

For posterity, the list is:
- THIS + group/mimic/all doesn't work
- STABLE + word causes an infinite loop (already reported: https://github.com/PlasmaFlare/plasma-baba-mods/issues/5)

**Comment by PlasmaFlare** [comment]
Yea. For the record, I do intend to fix them (which is why I reopened the issue). But the annoying thing is Hempuli plans at some point to redo word, which might make my current attempts to fix this moot. And I don't know when he plans to do it. So I'm just twiddling my thumbs right now :/

**Comment by PlasmaFlare** [comment]
Update: Released [1.5.9](https://github.com/PlasmaFlare/plasma-baba-mods/releases/tag/1.5.9), which fixes most cases with pointer nouns + mimic/group/all. See https://github.com/PlasmaFlare/plasma-baba-mods/issues/9.
