### ISSUE TITLE
STABLE doesn't preserve multiples of the same rule

### ISSUE THREAD

**Issue by LvlUniverse** [PlasmaFlare/plasma-baba-mods#7]
![error](https://user-images.githubusercontent.com/73113811/162616311-38a8d3ef-6c67-4795-b8ef-188ceefe7883.gif)

Objects that are STABLE should behave the same as they would if they were not made STABLE, so long as their rules aren't changed.

**Comment by LvlUniverse** [comment]
Further examples.
![alcoholism](https://user-images.githubusercontent.com/73113811/162633124-9823d2f4-3af6-4f0e-85d8-4422893b287e.gif)

![irreversible](https://user-images.githubusercontent.com/73113811/162633127-4ba2d2b1-166b-43cb-980f-4b6bc6f61e58.gif)

![final example](https://user-images.githubusercontent.com/73113811/162633131-73b39956-9ada-40f3-90b6-1b9c50ed9727.gif)

**Comment by PlasmaFlare** [comment]
Just fixed it in [1.5.6](https://github.com/PlasmaFlare/plasma-baba-mods/releases/tag/1.5.6).

Note that stacked empty stablerules currently do not work. This is a bug from the base game.

**Comment by LvlUniverse** [comment]
Well, not *all* stacked EMPTY stablerules. Just the ones that don't stack properly regardless  of stability.
![not all empty stablerules](https://user-images.githubusercontent.com/73113811/162634576-3f05a430-0494-44b1-8b10-efe3474a8fe0.gif)

**Comment by PlasmaFlare** [comment]
Yea I guess it's just some edge cases that Hempuli didn't consider when he first programmed empty. Either way, the mod should be able to at least pass on stacked stable properties to the main game.
